apiVersion: batch/v1
kind: Job
metadata:
  name: lsc-job
  namespace: lsc-ns
spec:
  template:
    spec:
      containers:
        - name: lsc-inject-job
          image: busybox
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "<h1>Example web page</h1><p>Example web page</p>" >> /usr/share/nginx/html/index.html
              echo "Job finished successfuly"
          volumeMounts:
            - name: lsc-volume
              mountPath: /usr/share/nginx/html
      restartPolicy: OnFailure
      volumes:
        - name: lsc-volume
          persistentVolumeClaim:
            claimName: lsc-pvc
