apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: lsc-pvc
  namespace: lsc-ns
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 200Mi
