apiVersion: v1
kind: Service
metadata:
  name: lsc-service
  namespace: lsc-ns
spec:
  selector:
    app: lsc-nginx-server
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
